# Project: xlib
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = alloc_m.o base_m.o cal_m.o main.o
LINKOBJ  = alloc_m.o base_m.o cal_m.o main.o
LIBS     = -L"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/lib" -L"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/include" -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/include" -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/program_setup/Dev-c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = xlib.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

alloc_m.o: alloc_m.c
	$(CC) -c alloc_m.c -o alloc_m.o $(CFLAGS)

base_m.o: base_m.c
	$(CC) -c base_m.c -o base_m.o $(CFLAGS)

cal_m.o: cal_m.c
	$(CC) -c cal_m.c -o cal_m.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
